### ISSUE TITLE
React.PropTypes is deprecated

### ISSUE THREAD

**Issue by soriac** [exponentjs/react-native-loading-container#14]
Hello, I was planning on using your component for a project, but after testing your example I get multiple yellow warnings. These warnings are generated because `React.PropTypes` is being manually called for the `indeterminate` prop on `ProgressBarAndroid`.

The same warning links me to https://fb.me/react-warning-dont-call-proptypes.

I tried to fix it by myself but I couldn't figure it out.

I've attached screenshots of the three warnings I get.

![screenshot_20170316-182525](https://cloud.githubusercontent.com/assets/12989318/24019264/24cbdabc-0a76-11e7-82e3-79e4696141fc.png)
![screenshot_20170316-182529](https://cloud.githubusercontent.com/assets/12989318/24019262/24c5cd2a-0a76-11e7-94ae-52c8bf2243e2.png)
![screenshot_20170316-182534](https://cloud.githubusercontent.com/assets/12989318/24019263/24c7c788-0a76-11e7-8a99-12b5d5bfba0e.png)

**Comment by soriac** [comment]
After creating and adding a custom loading overlay the warnings go away. I believe the cause of this issue is that the default loading overlay for the loading container is outdated.

**Comment by OwenFlood** [comment]
@brentvatne Does npm have the latest version? `npm i` is grabbing a version from before #12, which is triggering these warnings.

**Comment by brentvatne** [comment]
hello! can you submit a PR for this?

**Comment by OwenFlood** [comment]
The warnings should have been fixed by #12, but npm installing the latest version has outdated code. I figured that the latest changes just hadn't been published to npm yet? 

I'm not getting the errors when I `npm i https://github.com/expo/react-native-loading-container`

**Comment by brentvatne** [comment]
0.5.0 will fix this problem
